name: Python Containerization CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker Image from Dockerfile
      run: docker build -t gillrafay/python-auth-app:v1.0 -f ../../Dockerfile

    - name: Push Image to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - run: docker push gillrafay/python-auth-app:v1.0
    
